# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

addons:
  apt:
    packages:
      - librrd-dev

r_binary_packages: covr

matrix:
  include:
    - name: "Release"
      r: release
      
      after_success:
      - Rscript -e 'covr::codecov()'
      - find . -name testthat.Rout | xargs cat
      
      after_failure:
      - find . -name testthat.Rout | xargs cat
      
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true

    - name: "Old Release"
      r: oldrel

    - name: "Devel"
      r: devel

